# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  update-work-item-status:
    runs-on: ubuntu-latest

    env:
      organization: 'klevaorg'
      project: 'TraceableTribe'
      work-item-id: '7'
      new-status: 'Doing'
      closedstate: 'false'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update work item status
      uses: CanarysAutomations/pr-update-work-item-state@v1.4
